### ISSUE TITLE
1.12.2

### ISSUE THREAD

**Issue by arduino5144** [BigScary/GriefPreventionFlags#2]
Please may someone make it for 1.12.2?

**Comment by VoidAngel** [comment]
This should work but you will need to test it.
https://www.dropbox.com/s/0snuyhaka4o5s0f/GPFlags.jar?dl=0

**Comment by PiggiesGoSqueal** [comment]
Well, seems to work if this is the config file: https://pastebin.com/QfkspJcU
But I can't find any commands for this so I can't test further.

**Comment by VoidAngel** [comment]
Do these commands not work?
https://github.com/BigScary/GriefPreventionFlags/blob/master/plugin.yml

**Comment by arduino5144** [comment]
It works! Just followed you void angel!
